packageExtensions:
  relay-compiler@^12.0.0:
    dependencies:
      "@types/react-relay": ^11
      "@types/relay-runtime": ^12
      relay-compiler-language-typescript: ^15
      relay-config: ^12.0.0
      typescript: "^4.6.2"

yarnPath: .yarn/releases/yarn-3.2.0.cjs
